language: node_js
node_js: 8
cache: yarn
deploy:
  provider: script
  script: yarn sls deploy
  on:
    branch: master
  skip_cleanup: true
env:
  global:
  - secure: GJsUnnY+uLhHtiyjGfe5nzoNXl3JA21CBPHZzj9u+YMkwoN8czROBRIbqzlZDAMx7jD+/m9r3ESaaQJwlDhYct9YSs+qfgy3pV0dWwOK+BTt7n15Dk9WZbZmOFwLy0+W0rS0+ieX+znZxsoH6WyLhDlU4EHNuepiSi2NiHF3FRtwOz6ehBHdcUnp+g7xKnJ9ZN2CufQdMuiIFY51FYwkahzHoxiqghHNbVEkMcFSGCTY6d6hGQiS5jlRYXgFL+rAhhNvdCKvmy+i+Z07Iw7ibBmOkMw0479dNZ2JMYTf5GO49X/2+QcE/HX+pyja3Cq0hcK3ROVw8D2rTJSRLDM9u1AFURKXDSQ3CFLVsbDw/WY2ZH/xTLz9gcSE1W4IDnF/Ov1bispYi59ZaFGEzL2EpmU678EDYMLsW9JpHGUMX75KoNhIqN1rn7vc3pUNifD51LsJWuXVVO5VQEjQlyjgGzyTBHuLUW6NWJ6g6M9OZfbno21cWc6nqb77uug/VuuWEs70yRHYq2oNPmeYvo6sE4o9eKkaZuJvMHaNeBJ1DXVV9hjn1zhF+7wo21g7GhM/9QslEnoEh57p9VFGZBItmBDlGO22MIUJh1gaZjs6E9trkQGIoT1ybJ2tKpqC5GtZ5ozflEM+9B2xQ+TXv/p0ynY5dFvvWiVAsITGhhpjrsM=
  - secure: lmQ3fgI2NWERnOWl9OO4insf6STx5X9M/ueILqrJJdRjc4Qjar1lu5quKH0qZlqigZ9v5uuE4FNn3HFr/gQfm4iJm3fVWeFrr1rvijYEjqXSEIyHVUkAweaICKAgLijmcYhmdhsTCTrKP03+4pMzCy1Yw/JR9o/TIHrY36G1Q/7RT3Q2OqJnJAPlA9rIxlW7YXcDoYLGPs+XF7zHNOZl4xZHJ4AX3dNaeBqxUM7419gxAZTsAWRtm+WynFTeu4MXJn8WjGpNyiHhmPNs7sXDLFwmNDi4K7A9NWkp+nK6uCrxqcP4FaDHNIt+o8BSFI7Dc6nuCPyT/Zn8xdSxSAcjovFvj2OzUg00Eh3sQP3kYLGaMGAOibLloQErN+Ozv6Oj4WU3dViEZCoY+Kk5/Yh8e/OO//QyppG01ujsXopiHpSccvjFxKqgtimhJpylTlJplE5XvEs95kvqSk3hieP6Q2Jm9BEPCnAtVIF5qbLcBKzvB86zC3sjpYrrpHKnT9XJGlA6XqYbBcDZCTZXgEMjmoyxY4nIN2WNOaIUVhEhbePwOxauUI9KbOlHwcoO9Gb6jIKQR/gaIECTlWeewh5Y6qhIptH/mnSeXU+bZ9DkPvuugsFEafJAosiXnARGF4QN4j9mIU5E3DO64sG2gLlsZJ7ZlmTTwpHFbIwgGlSWFvo=
