language: node_js
node_js: 8
cache: yarn
branches:
  only:
    master
deploy:
  provider: script
  script: yarn sls deploy
  on:
    branch: master
  skip_cleanup: true
env:
  global:
  - secure: 1pOUfhJb1uBSbF5ZHK0cXd33OiBrVe0IFCdmloLW/usPcIzKZQRozA6mC2C5MGOUjaTbWURpdDZOhnYxh7RQqZfkypAJkPJjU2wjpVhj2G9Q62EmTYsuIadXY3eCAZPMSWtm3HlIc8J8umDxBQ9Oiynw/xR2bhbj1ZJPpySdSYO592P7qu0HQZjK0l6pWkPMbPoAWKLdC7FbPl74bJdxnd53pn+7ja8dA7kZVvP8Q6S7jSDPhNGwMzi3tvWPnbKdAoEDQL3NGzC3ZwlEn4xlNS92+DuG5WuuvdymhxaT86pqUXgrAbAFfPJrACDYt5YktlQlP89l1o7vtgkV7wveE86vnslm2MfBa4L9J5mGx0CexOETVDo3yfOnUS6lKK+txDHt6CnFhH5yUgFcsppN41PeDX83f4/IkZDU66HlDzC4w+dMRF1sdHMpZlKVjTTDetMDiiIJ2p3539Mqt2eomiqJMvHQl8Q36sRRuJ/b9p3Q3I7QicgYdp8KOOCsMjRWfYgl8D+PgERnMasTRbpff//hYHjte1lfWhHUPnh1BccMhXbnUvQRrlmV6pCFibG4rEbxB+iY53iqDnhPG/HLfkO3wWgj6XvyD0GT/9MUyAmk1jwLGatEnU1PYOiJE2Z5hj7mNkTJkw3Q0sjMi2SEJdksx+OCBKTx2DZ3PfsrS4g=
  - secure: RlBKuqRjheM4SJrHbFgtuM8PDaRnlCMyaVy83BBL7ywnSopIvnyafho0KbkWmjuYv0899WoK2ZIFjlQUf80oZv01ZGXasDWwOnAUX36cUMoDyCMWI7HScLPoRZ3CVVzQX7QZRRQ9y8XZKzKcfUjNn6zsQgoo+5ixH5vEzJCkncJ1IsYdevxlE4zrzmd/PFZ9jUpGFG8C3JgxnFhfo6cOnc11qqV4kSSQKJysWs2Pm3JGYDn+t+XiN7YFHJixlVeNKY8fE55Pa6+FtiBHyEvdld9djwuQqRXll+NFPQwXAGYpE6yU3Kj9BEmHKvc/s5M9fuhlax39BDOQYBvS/Z5SrJ+JtoNvBiqmhihYb/aEOvGvbuNVDjhMnRF36MZtqFusx4M8euvWpUIyToTOF6XbhF3GS7yC1BVhJ0vNX0PxkfO6jZmj96PDwBvzJD5PP/5C3n4XRxQ14S+JTYpDKb0jvKeckl7KQb86uzBVoRA7WhzGYCo+/cb7g0SBjrjzPZPTxfub/JKEyNJZWdfNoKfB8tmHyFQAX5NAEhPMRIQAOd2H9jFzrXXNgFHNQhB+l/0B4kP9q/UImB+/vujjr8CnNpbGAzZ4biwEDpsJWTFoXv7b48ZFy8kGAmgqgc7yOnZRQOkwfffG2hpn6Rt3zZULUh5IRzAk8DAEXj3vU4PVvN0=
